tasks:
  - name: gitlab-package
    actions:
      - description: Deploy the UDS Gitlab Zarf Package
        cmd: zarf package deploy zarf-package-gitlab-${UDS_ARCH}-*.tar.zst --confirm --no-progress

  - name: gitlab-test-bundle
    actions:
      - description: Deploy the UDS bundle with Gitlab and its dependencies
        cmd: UDS_CONFIG=bundle/uds-config.yaml uds deploy bundle/uds-bundle-gitlab-test-${UDS_ARCH}-*.tar.zst --confirm --no-progress
