name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:

  # This allows other repositories to call this workflow in a reusable way
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Lint
    permissions:
      contents: read # Allows reading the repo contents

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@42196a596353dc9f8acb21a6a86b5d4a4f7ee76f # v1.14.2
        with:
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Install lint deps
        run: |
          uds run lint:deps

      - name: Lint the repository
        run: |
          uds run lint:yaml
