name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: uds-ubuntu-big-boy-8-core
    timeout-minutes: 25
    strategy:
      matrix:
        flavor: [upstream, registry1]
        type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@e84f5624ec53b7e126166ae4d9f1144ba8afeac6 # v1.14.1
        with:
          username: ${{secrets.IRON_BANK_ROBOT_USERNAME}}
          password: ${{secrets.IRON_BANK_ROBOT_PASSWORD}}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@e84f5624ec53b7e126166ae4d9f1144ba8afeac6 # v1.14.1
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@e84f5624ec53b7e126166ae4d9f1144ba8afeac6 # v1.14.1
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
